services:
  film:
    container_name: filmapp
    build: .
    image: filmapp:v1
    ports:
      - 80:80
    expose:
      - 80
    networks:
      - internalnet


networks:
  internalnet:
    driver: bridge
